In [1]:
import numpy as np

In [47]:
size = 3
graph_conn = {}
# generate all possible connections except itself
for i in range(1, size+1):
    graph_conn[i] = [n for n in range(1, size+1) if n != i]

In [48]:
graph_conn

{1: [2, 3], 2: [1, 3], 3: [1, 2]}

In [49]:
import itertools

a = [0,1,1]

arcs = np.zeros(size).astype(int)
for root_dep_i in range(size):
    arcs[root_dep_i] = 0

    nodes_list = [l for l in range(1, size+1) if l != root_dep_i + 1]

    for indexes in itertools.product(range(size-1), repeat=size-1):
        for i, node in enumerate(indexes):
            arcs_index = nodes_list[i]
            arcs[arcs_index-1] = graph_conn[arcs_index][node]

        # check if one is connected to root_dep
        if root_dep_i + 1 in arcs:
            a.append(list(arcs))

    break
print(np.array(a))
len(a)

[[0 1 1]
 [0 1 2]
 [0 3 1]]


3

In [ ]:
import itertools

arcs = np.zeros(size).astype(int)
for root_dep_i in range(1, size + 1):
    arcs[root_dep_i] = 0

    nodes_list = [l for l in range(1, size+1) if l != root_dep_i]
    for indexes in itertools.product(range(size-1), repeat=size-1):
        for i, node in enumerate(indexes):
            arcs_index = nodes_list[i]
            arcs[arcs_index] = graph_conn[arcs_index][node]

        # check if one is connected to root_dep
        if root_dep_i in arcs

## Testing ConllDataset

In [29]:
from src.dataset import ConllDataset

original_file = './data/wsj_dev.conll06.pred'
conll_dataset = ConllDataset(original_file)

Test writing to new file

In [30]:
conll_dataset.write(filepath='./test.conll06')

## Access sentence

In [31]:
from src.dataset import ConllDataset

original_file = './data/wsj_dev.conll06.pred'
conll_dataset = ConllDataset(original_file)

In [4]:
conll_dataset[0].sentence

id         form        lemma  pos xpos morph.  head    rel deps misc
0    1          The          the   DT    _      _     2   NMOD    _    _
1    2      economy      economy   NN    _      _     4   NMOD    _    _
2    3           's           's  POS    _      _     2   NMOD    _    _
3    4  temperature  temperature   NN    _      _     5    SBJ    _    _
4    5         will         will   MD    _      _     0   ROOT    _    _
5    6           be           be   VB    _      _     5     VC    _    _
6    7        taken         take  VBN    _      _     6     VC    _    _
7    8         from         from   IN    _      _     7    ADV    _    _
8    9      several      several   JJ    _      _    11   NMOD    _    _
9   10      vantage      vantage   NN    _      _    11   NMOD    _    _
10  11       points        point  NNS    _      _     8   PMOD    _    _
11  12         this         this   DT    _      _    13   NMOD    _    _
12  13         week         week   NN    _      _     7    OBJ    _    _
13  14            ,            ,    ,    _      _     7      P    _    _
14  15         with         with   IN    _      _     7    ADV    _    _
15  16     readings      reading  NNS    _      _    15   PMOD    _    _
16  17           on           on   IN    _      _    16   NMOD    _    _
17  18        trade        trade   NN    _      _    17   PMOD    _    _
18  19            ,            ,    ,    _      _    18      P    _    _
19  20       output       output   NN    _      _    18   CONJ    _    _
20  21            ,            ,    ,    _      _    20      P    _    _
21  22      housing      housing   NN    _      _    20   CONJ    _    _
22  23          and          and   CC    _      _    22  COORD    _    _
23  24    inflation    inflation   NN    _      _    23   CONJ    _    _
24  25            .            .    .    _      _     5      P    _    _

## Evaluation

In [32]:
from src.dataset import ConllDataset

gold_file = './data/wsj_dev.conll06.gold'
prediction_file = './data/wsj_dev.conll06.pred'

conll_gold = ConllDataset(gold_file)
conll_prediction = ConllDataset(prediction_file)

In [33]:
from src.evaluation import uas, las

In [34]:
uas(conll_gold, conll_prediction)

0.8974243278811807

In [35]:
las(conll_gold, conll_prediction)

0.8811430720060162